version: '3'
services:
  mysql:
    build:
      context: ../bot-detector-mysql
      dockerfile: Dockerfile
    image: bot-detector/bd-mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ../bot-detector-mysql/mount:/var/lib/mysql 
      - '../bot-detector-mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    ports:
      - "3306:3306"
    networks:
      - botdetector-network

networks:
  botdetector-network: