version: '3'
services:
  mysql:
    build:
      context: .
    image: bot-detector/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_bot_buster
    volumes:
      - ./mount:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - botdetector-network

networks:
  botdetector-network:
